#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : mbedtls
Version  : 3.0.0
Release  : 225
URL      : https://github.com/ARMmbed/mbedtls/archive/refs/tags/v3.0.0.tar.gz
Source0  : https://github.com/ARMmbed/mbedtls/archive/refs/tags/v3.0.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0
Requires: mbedtls-bin = %{version}-%{release}
Requires: mbedtls-lib = %{version}-%{release}
BuildRequires : binutils-dev
BuildRequires : buildreq-cmake
BuildRequires : gcc
BuildRequires : gcc-dev
BuildRequires : gcc-doc
BuildRequires : gcc-libs-math
BuildRequires : gcc-libubsan
BuildRequires : gcc-locale
BuildRequires : glibc-dev
BuildRequires : openssl-dev
BuildRequires : openssl-staticdev
BuildRequires : pkg-config-dev
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : readline-dev
BuildRequires : tcl
BuildRequires : tcl-dev
BuildRequires : tcl-staticdev
BuildRequires : xz-dev
BuildRequires : xz-staticdev
BuildRequires : zlib-dev
BuildRequires : zlib-staticdev

%description
The documents in this directory are proposed specifications for Mbed
TLS features. They are not implemented yet, or only partially
implemented. Please follow activity on the `development` branch of
Mbed TLS if you are interested in these features.

%package bin
Summary: bin components for the mbedtls package.
Group: Binaries

%description bin
bin components for the mbedtls package.


%package dev
Summary: dev components for the mbedtls package.
Group: Development
Requires: mbedtls-lib = %{version}-%{release}
Requires: mbedtls-bin = %{version}-%{release}
Provides: mbedtls-devel = %{version}-%{release}
Requires: mbedtls = %{version}-%{release}

%description dev
dev components for the mbedtls package.


%package lib
Summary: lib components for the mbedtls package.
Group: Libraries

%description lib
lib components for the mbedtls package.


%package staticdev
Summary: staticdev components for the mbedtls package.
Group: Default
Requires: mbedtls-dev = %{version}-%{release}

%description staticdev
staticdev components for the mbedtls package.


%prep
%setup -q -n mbedtls-3.0.0
cd %{_builddir}/mbedtls-3.0.0

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1625793896
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
## altflags_pgo content
## pgo generate
export PGO_GEN="-fprofile-generate=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-update=atomic -fprofile-arcs -ftest-coverage --coverage -fprofile-partial-training"
export CFLAGS_GENERATE="-g -O3 -Wl,--as-needed --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -fomit-frame-pointer -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables -pthread -static-libstdc++ -static-libgcc $PGO_GEN"
export FCFLAGS_GENERATE="-g -O3 -Wl,--as-needed --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
export FFLAGS_GENERATE="-g -O3 -Wl,--as-needed --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
export CXXFLAGS_GENERATE="-g -O3 -Wl,--as-needed --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -fvisibility-inlines-hidden -pipe -ffat-lto-objects -flto=16 -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables $PGO_GEN"
export LDFLAGS_GENERATE="-g -O3 -Wl,--as-needed --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -flto=16 -fPIC -fomit-frame-pointer -Wl,--build-id=sha1 -fdevirtualize-at-ltrans -Wl,-z,now -Wl,-z,relro -Wl,-sort-common -fasynchronous-unwind-tables -pthread -static-libstdc++ -static-libgcc -lpthread $PGO_GEN"
## pgo use
## -fno-tree-vectorize: disable -ftree-vectorize thus disable -ftree-loop-vectorize and -ftree-slp-vectorize
## -funroll-loops maybe dangerous
## -Wl,-z,max-page-size=0x1000
export PGO_USE="-fprofile-use=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-correction -fprofile-partial-training"
export CFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export FCFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export FFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export CXXFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc $PGO_USE"
export LDFLAGS_USE="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -lpthread $PGO_USE"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
#%global _disable_maintainer_mode %{nil}
#
export CCACHE_DISABLE=true
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
#export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
#export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#export CCACHE_LOGFILE=/var/tmp/ccache/cache.debug
#export CCACHE_DEBUG=true
#export CCACHE_NODIRECT=true
#
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/dri:/usr/lib64/haswell:/usr/lib64:/usr/lib:/usr/share"
#
export LIBRARY_PATH="$LIBRARY_PATH:/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/dri:/usr/lib64/haswell:/usr/lib64:/usr/lib:/usr/share"
#
export PATH="$PATH:/usr/local/cuda/bin:/usr/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
#
export CPATH="$CPATH:/usr/local/cuda/include"
#
export DISPLAY=:0
export __GL_ALLOW_UNOFFICIAL_PROTOCOL=1
export __GL_SYNC_TO_VBLANK=0
export __GL_SYNC_DISPLAY_DEVICE=DFP-1
export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=DFP-1
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH=/usr/share/defaults/fonts
## altflags_pgo end
if [ ! -f statuspgo ]; then
echo PGO Phase 1
export CFLAGS="${CFLAGS_GENERATE}"
export CXXFLAGS="${CXXFLAGS_GENERATE}"
export FFLAGS="${FFLAGS_GENERATE}"
export FCFLAGS="${FCFLAGS_GENERATE}"
export LDFLAGS="${LDFLAGS_GENERATE}"
%cmake .. -DUSE_SHARED_MBEDTLS_LIBRARY=ON \
-DUSE_STATIC_MBEDTLS_LIBRARY=ON \
-DENABLE_TESTING=ON
## make_prepend content
sd -- " \-O2" " -O3" $(fd -uu --glob Makefile)
sd -- " \-O2" " -O3" $(fd -uu --glob *.make)
sd -- " \-O2" " -O3" $(fd -uu --glob link.txt)
## make_prepend end
make  %{?_smp_mflags}    V=1 VERBOSE=1

ctest --parallel 16 -V --progress --timeout 400 || :
find . -type f,l -not -name '*.gcno' -not -name 'statuspgo*' -delete -print
echo USED > statuspgo
fi
if [ -f statuspgo ]; then
echo PGO Phase 2
export CFLAGS="${CFLAGS_USE}"
export CXXFLAGS="${CXXFLAGS_USE}"
export FFLAGS="${FFLAGS_USE}"
export FCFLAGS="${FCFLAGS_USE}"
export LDFLAGS="${LDFLAGS_USE}"
%cmake .. -DUSE_SHARED_MBEDTLS_LIBRARY=ON \
-DUSE_STATIC_MBEDTLS_LIBRARY=ON \
-DENABLE_TESTING=OFF
## make_prepend content
sd -- " \-O2" " -O3" $(fd -uu --glob Makefile)
sd -- " \-O2" " -O3" $(fd -uu --glob *.make)
sd -- " \-O2" " -O3" $(fd -uu --glob link.txt)
## make_prepend end
make  %{?_smp_mflags}    V=1 VERBOSE=1
fi
popd

%install
export SOURCE_DATE_EPOCH=1625793896
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/cmake/MbedTLSConfig.cmake
/usr/cmake/MbedTLSConfigVersion.cmake
/usr/cmake/MbedTLSTargets-relwithdebinfo.cmake
/usr/cmake/MbedTLSTargets.cmake

%files bin
%defattr(-,root,root,-)
/usr/bin/benchmark
/usr/bin/cert_app
/usr/bin/cert_req
/usr/bin/cert_write
/usr/bin/crl_app
/usr/bin/crypt_and_hash
/usr/bin/crypto_examples
/usr/bin/dh_client
/usr/bin/dh_genprime
/usr/bin/dh_server
/usr/bin/dtls_client
/usr/bin/dtls_server
/usr/bin/ecdh_curve25519
/usr/bin/ecdsa
/usr/bin/gen_entropy
/usr/bin/gen_key
/usr/bin/gen_random_ctr_drbg
/usr/bin/generic_sum
/usr/bin/hello
/usr/bin/key_app
/usr/bin/key_app_writer
/usr/bin/key_ladder_demo
/usr/bin/key_ladder_demo.sh
/usr/bin/mini_client
/usr/bin/mpi_demo
/usr/bin/pem2der
/usr/bin/pk_decrypt
/usr/bin/pk_encrypt
/usr/bin/pk_sign
/usr/bin/pk_verify
/usr/bin/psa_constant_names
/usr/bin/query_compile_time_config
/usr/bin/req_app
/usr/bin/rsa_decrypt
/usr/bin/rsa_encrypt
/usr/bin/rsa_genkey
/usr/bin/rsa_sign
/usr/bin/rsa_sign_pss
/usr/bin/rsa_verify
/usr/bin/rsa_verify_pss
/usr/bin/selftest
/usr/bin/ssl_client1
/usr/bin/ssl_client2
/usr/bin/ssl_context_info
/usr/bin/ssl_fork_server
/usr/bin/ssl_mail_client
/usr/bin/ssl_pthread_server
/usr/bin/ssl_server
/usr/bin/ssl_server2
/usr/bin/strerror
/usr/bin/udp_proxy
/usr/bin/zeroize

%files dev
%defattr(-,root,root,-)
/usr/include/mbedtls/aes.h
/usr/include/mbedtls/aria.h
/usr/include/mbedtls/asn1.h
/usr/include/mbedtls/asn1write.h
/usr/include/mbedtls/base64.h
/usr/include/mbedtls/bignum.h
/usr/include/mbedtls/build_info.h
/usr/include/mbedtls/camellia.h
/usr/include/mbedtls/ccm.h
/usr/include/mbedtls/chacha20.h
/usr/include/mbedtls/chachapoly.h
/usr/include/mbedtls/check_config.h
/usr/include/mbedtls/cipher.h
/usr/include/mbedtls/cmac.h
/usr/include/mbedtls/compat-2.x.h
/usr/include/mbedtls/config_psa.h
/usr/include/mbedtls/ctr_drbg.h
/usr/include/mbedtls/debug.h
/usr/include/mbedtls/des.h
/usr/include/mbedtls/dhm.h
/usr/include/mbedtls/ecdh.h
/usr/include/mbedtls/ecdsa.h
/usr/include/mbedtls/ecjpake.h
/usr/include/mbedtls/ecp.h
/usr/include/mbedtls/entropy.h
/usr/include/mbedtls/error.h
/usr/include/mbedtls/gcm.h
/usr/include/mbedtls/hkdf.h
/usr/include/mbedtls/hmac_drbg.h
/usr/include/mbedtls/mbedtls_config.h
/usr/include/mbedtls/md.h
/usr/include/mbedtls/md5.h
/usr/include/mbedtls/memory_buffer_alloc.h
/usr/include/mbedtls/net_sockets.h
/usr/include/mbedtls/nist_kw.h
/usr/include/mbedtls/oid.h
/usr/include/mbedtls/pem.h
/usr/include/mbedtls/pk.h
/usr/include/mbedtls/pkcs12.h
/usr/include/mbedtls/pkcs5.h
/usr/include/mbedtls/platform.h
/usr/include/mbedtls/platform_time.h
/usr/include/mbedtls/platform_util.h
/usr/include/mbedtls/poly1305.h
/usr/include/mbedtls/private_access.h
/usr/include/mbedtls/psa_util.h
/usr/include/mbedtls/ripemd160.h
/usr/include/mbedtls/rsa.h
/usr/include/mbedtls/sha1.h
/usr/include/mbedtls/sha256.h
/usr/include/mbedtls/sha512.h
/usr/include/mbedtls/ssl.h
/usr/include/mbedtls/ssl_cache.h
/usr/include/mbedtls/ssl_ciphersuites.h
/usr/include/mbedtls/ssl_cookie.h
/usr/include/mbedtls/ssl_ticket.h
/usr/include/mbedtls/threading.h
/usr/include/mbedtls/timing.h
/usr/include/mbedtls/version.h
/usr/include/mbedtls/x509.h
/usr/include/mbedtls/x509_crl.h
/usr/include/mbedtls/x509_crt.h
/usr/include/mbedtls/x509_csr.h
/usr/include/psa/crypto.h
/usr/include/psa/crypto_builtin_composites.h
/usr/include/psa/crypto_builtin_primitives.h
/usr/include/psa/crypto_compat.h
/usr/include/psa/crypto_config.h
/usr/include/psa/crypto_driver_common.h
/usr/include/psa/crypto_driver_contexts_composites.h
/usr/include/psa/crypto_driver_contexts_primitives.h
/usr/include/psa/crypto_extra.h
/usr/include/psa/crypto_platform.h
/usr/include/psa/crypto_se_driver.h
/usr/include/psa/crypto_sizes.h
/usr/include/psa/crypto_struct.h
/usr/include/psa/crypto_types.h
/usr/include/psa/crypto_values.h
/usr/lib64/libmbedcrypto.so
/usr/lib64/libmbedtls.so
/usr/lib64/libmbedx509.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmbedcrypto.so.10
/usr/lib64/libmbedcrypto.so.3.0.0
/usr/lib64/libmbedtls.so.16
/usr/lib64/libmbedtls.so.3.0.0
/usr/lib64/libmbedx509.so.3.0.0
/usr/lib64/libmbedx509.so.4

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libmbedcrypto.a
/usr/lib64/libmbedtls.a
/usr/lib64/libmbedx509.a
